### ISSUE TITLE
Latest release crashes with Wurst in 1.15.2

### ISSUE THREAD

**Issue by ItsYoungDaddy** [BleachDrinker420/bleachhack-1.14#104]
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/F/New Folder/mienkraft/MultiMC/instances/currently smokin meth/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_261, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/F/New Folder/mienkraft/MultiMC/instances/currently smokin meth/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/intermediary/1.15.2/intermediary-1.15.2.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.2.64/tiny-remapper-0.2.2.64.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/ow2/asm/asm/8.0/asm-8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/ow2/asm/asm-analysis/8.0/asm-analysis-8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/ow2/asm/asm-commons/8.0/asm-commons-8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/ow2/asm/asm-tree/8.0/asm-tree-8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/ow2/asm/asm-util/8.0/asm-util-8.0.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/fabric-loader/0.9.0+build.204/fabric-loader-0.9.0+build.204.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/F/New Folder/mienkraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] bleachhack-b13.2-1.15.2
  [❌] bleachhack-b13.3-1.15.2.jar (disabled)
  [✔️] fabric-api-0.14.0+build.317-1.15
  [❌] ViaBackwards-3.1.0-SNAPSHOT.jar (disabled)
  [✔️] ViaFabric-0.2.4-SNAPSHOT+build-284.1-mc-1.14-1.15
  [❌] viarewind-fabric-1.5.1-SNAPSHOT.jar (disabled)
  [✔️] ViaVersion-3.0.0-SNAPSHOT
  [✔️] Wurst-Client-v7.4-MC1.15.2
  [❌] wwe_1.15.2.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/F/New Folder/mienkraft/MultiMC/instances/currently smokin meth/.minecraft --assetsDir C:/Users/F/New Folder/mienkraft/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx3944m, -Duser.language=en]

Minecraft process ID: 2412

Using onesix launcher.

[08:37:05] [main/INFO]: Loading for game Minecraft 1.15.2
[08:37:06] [main/INFO]: [FabricLoader] Loading 46 mods: minecraft@1.15.2, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-keybindings-v0@0.2.0+2af3af910c, bleachhack@13.37, viafabric@0.2.4-SNAPSHOT+build-284.1-mc-1.14-1.15, fabric-command-api-v1@1.0.2+2aebb7ff0c, fabricloader@0.9.0+build.204, fabric-tool-attribute-api-v1@1.1.0+3e5587510c, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-object-builder-api-v1@1.2.1+e7a4edb30c, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.3.0+fac69e320c, fabric-item-api-v1@1.0.0+2f23104b0c, cotton-client-commands@1.0.0+1.15.2, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@1.0.0+2a034f0a0c, fabric-key-binding-api-v1@1.0.0+2af3af910c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-textures-v0@1.0.4+821cdba70c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-commands-v0@0.2.0+2e0c4ff50c, com_github_vatuu_discord-rpc@1.6.2, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-lifecycle-events-v1@1.0.0+451a3d520c, fabric-mining-levels-v0@0.1.2+ec951ea40c, fabric-climbable-api-v1@1.0.0+6ffe71e20c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric-events-lifecycle-v0@0.2.0+2f23104b0c, fabric@0.14.0+build.317-1.15, wurst@v7.4-MC1.15.2, viaversion@3.0.2-SNAPSHOT, fabric-particles-v1@0.2.1+b2771bde0c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.2.0+0121bd900c, fabric-object-builders-v0@0.5.1+3e5587510c, fabric-networking-v0@0.1.10+d487f0ee0c
[08:37:06] [main/WARN]: Mod `wurst` (v7.4-MC1.15.2) does not respect SemVer - comparison support is limited.
[08:37:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/F/New Folder/mienkraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[08:37:11] [main/WARN]: Method overwrite conflict for method_21825 in bleachhack.mixins.json:MixinClientPlayerEntity, previously written by net.wurstclient.mixin.ClientPlayerEntityMixin. Skipping method.
[08:37:11] [main/WARN]: @Redirect conflict. Skipping bleachhack.mixins.json:MixinClientPlayerEntity->@Redirect::tickMovement_isUsingItem(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by wurst.mixins.json:ClientPlayerEntityMixin->@Redirect::wurstIsUsingItem(Lnet/minecraft/class_746;)Z with priority 1000
[08:37:12] [main/INFO]: Setting user: Methsploit
[08:37:18] [pool-3-thread-1/INFO]: Loading 1.12.2 -> 1.13 mappings...
[08:37:19] [pool-3-thread-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[08:37:19] [pool-3-thread-3/INFO]: Loading 1.14.4 -> 1.15 mappings...
[08:37:19] [pool-3-thread-4/INFO]: Loading 1.15 -> 1.16 mappings...
[08:37:19] [ViaFabric-1/INFO]: ViaVersion detected server version: 1.15.2(578)
[08:37:19] [main/INFO]: [STDOUT]: Starting Wurst Client...
[08:37:19] [pool-3-thread-1/INFO]: Loading block connection mappings ...
[08:37:23] [main/INFO]: [Indigo] Registering Indigo renderer!
[08:37:24] [ViaFabric-1/WARN]: You are running a development version, please report any bugs to GitHub.
[08:37:25] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[08:37:37] [main/WARN]: @Redirect conflict. Skipping bleachhack.mixins.json:MixinGameRenderer->@Redirect::nauseaWobble(FFF)F with priority 1000, already redirected by wurst.mixins.json:GameRendererMixin->@Redirect::wurstNauseaLerp(FFF)F with priority 1000
[08:37:37] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector nauseaWobble(FFF)F in bleachhack.mixins.json:MixinGameRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap BleachHack-Fabric-1.15-refmap.json
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[08:37:37] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[08:37:37] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[08:37:37] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[08:37:37] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:492)
[08:37:37] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:166)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[08:37:37] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[08:37:37] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:37:37] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[08:37:37] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[08:37:37] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[08:37:37] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/27/20 8:37 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_310.<init>(class_310.java:492)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector nauseaWobble(FFF)F in bleachhack.mixins.json:MixinGameRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap BleachHack-Fabric-1.15-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_310.<init>(class_310.java:492)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1487542056 bytes (1418 MB) / 1908932608 bytes (1820 MB) up to 3676307456 bytes (3506 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3944m
	Fabric Mods: 
		bleachhack: BleachHack 13.37
		com_github_vatuu_discord-rpc: discord-rpc 1.6.2
		cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
		fabric: Fabric API 0.14.0+build.317-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+2f23104b0c
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+2f23104b0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+0121bd900c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+2af3af910c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+2af3af910c
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+451a3d520c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+d487f0ee0c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.2.1+b2771bde0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.9.0+build.204
		minecraft: Minecraft 1.15.2
		viafabric: ViaFabric 0.2.4-SNAPSHOT+build-284.1-mc-1.14-1.15
		viaversion: ViaVersion API 3.0.2-SNAPSHOT
		wurst: Wurst Client v7.4-MC1.15.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX550/550 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\F\New Folder\mienkraft\MultiMC\instances\currently smokin meth\.minecraft\crash-reports\crash-2020-07-27_08.37.37-client.txt
Process exited with code -1.

**Comment by BleachDrinker420** [comment]
this is already fixed in the dev builds

**Comment by BleachDrinker420** [comment]
[bleachhack-1.15.2-commit-544.zip](https://github.com/BleachDrinker420/bleachhack-1.14/files/4983178/bleachhack-1.15.2-commit-544.zip)
here is the latest build if you are too lazy to build it yourself

**Comment by ItsYoungDaddy** [comment]
Oh thank you, ive been trying to build it but im very bad at coding/using an IDE. Been trying to figure out how to do it for a few hours now

**Comment by BleachDrinker420** [comment]
if you are on windows, you can just click the build.bat to build bleachhack

**Comment by ItsYoungDaddy** [comment]
I do that within the ide or the folder?

**Comment by ItsYoungDaddy** [comment]
I do that within the ide or the folder?
