### ISSUE TITLE
Compatibility With Kotlin

### ISSUE THREAD

**Issue by DotDivee** [BleachDrinker420/bleachhack-1.14#169]
So I wanted to try programming in kotlin because i like it more but every time i build the jar and run minecraft i get a noClassDef Error. Whats interesting is that this is only a problem outside of the IDE; when i build and run in intellij everything works fine. This is the crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 15/11/20 19:41
Description: Unexpected error

java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at bleach.hack.module.mods.PlayerFrameKt.onDrawOverlay(PlayerFrameKt.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraft.class_329.handler$zfo001$render(class_329.java:1845)
	at net.minecraft.class_329.method_1753(class_329.java:378)
	at net.minecraft.class_757.method_3192(class_757.java:597)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at bleach.hack.module.mods.PlayerFrameKt.onDrawOverlay(PlayerFrameKt.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraft.class_329.handler$zfo001$render(class_329.java:1845)
	at net.minecraft.class_329.method_1753(class_329.java:378)

-- Affected level --
Details:
	All players: 35 total; [class_746['Divee'/8377, l='ClientLevel', x=241.82, y=35.00, z=-52.42], class_745['FoxyRiverDemon'/6368, l='ClientLevel', x=214.85, y=15.08, z=-65.26], class_745['ak4slasher'/3688, l='ClientLevel', x=239.54, y=35.00, z=-43.99], class_745['Keiruuh'/8242, l='ClientLevel', x=233.26, y=35.00, z=-37.97], class_745['SnackMeisterFin'/8318, l='ClientLevel', x=236.51, y=35.00, z=-40.71], class_745['yober'/8368, l='ClientLevel', x=225.86, y=36.00, z=-36.61], class_745['MasterArin'/7227, l='ClientLevel', x=238.41, y=35.00, z=-21.21], class_745['tacky47'/8280, l='ClientLevel', x=238.04, y=35.00, z=-19.30], class_745['CollinsBoyz8'/7163, l='ClientLevel', x=228.61, y=35.00, z=-8.72], class_745['shiftyfootball'/451, l='ClientLevel', x=242.66, y=35.00, z=-53.18], class_745['LemoncloudGT_YT'/7983, l='ClientLevel', x=243.27, y=35.00, z=-54.47], class_745['Doczan'/469, l='ClientLevel', x=243.36, y=35.00, z=-53.49], class_745['BabySimp'/6691, l='ClientLevel', x=242.16, y=35.00, z=-51.80], class_745['FakeSam'/8355, l='ClientLevel', x=243.21, y=35.00, z=-53.26], class_745['Topfootballer'/8269, l='ClientLevel', x=242.29, y=35.00, z=-53.57], class_745['KillerDragon24'/8047, l='ClientLevel', x=243.24, y=35.00, z=-51.71], class_745['HippiePandaYT'/8327, l='ClientLevel', x=242.70, y=35.00, z=-49.18], class_745['*Dionel9061'/8357, l='ClientLevel', x=248.82, y=35.00, z=-55.59], class_745['Pqmkin'/8014, l='ClientLevel', x=241.35, y=35.00, z=-53.87], class_745['LegendNugget'/8347, l='ClientLevel', x=271.99, y=36.64, z=-42.44], class_745['JoshKosh113'/8375, l='ClientLevel', x=241.51, y=35.00, z=-50.59], class_745['Boris_De_Koe'/8376, l='ClientLevel', x=240.99, y=35.20, z=-47.70], class_745['Binny_K'/7250, l='ClientLevel', x=242.14, y=35.00, z=-39.40], class_745['itsapancake'/8321, l='ClientLevel', x=247.37, y=35.00, z=-38.07], class_745['gameplayer1188'/8370, l='ClientLevel', x=245.33, y=35.00, z=-46.51], class_745['Baguette_Kid'/8361, l='ClientLevel', x=242.28, y=35.00, z=-32.56], class_745['sagiyy55'/8326, l='ClientLevel', x=240.30, y=35.00, z=-22.87], class_745['Sharktail100'/8324, l='ClientLevel', x=242.37, y=35.00, z=-22.69], class_745['borkhimself'/8378, l='ClientLevel', x=241.39, y=35.00, z=-54.46], class_745['aurorarori97'/8379, l='ClientLevel', x=240.90, y=35.00, z=-54.01], class_745['_Heiress'/8380, l='ClientLevel', x=241.07, y=35.00, z=-52.49], class_745['caitlyncianci'/8381, l='ClientLevel', x=241.92, y=35.00, z=-51.67], class_745['GolemGreat122'/8382, l='ClientLevel', x=242.08, y=35.00, z=-51.91], class_745['keqio'/8360, l='ClientLevel', x=253.62, y=35.00, z=-10.53], class_745['popper11'/8383, l='ClientLevel', x=240.78, y=35.00, z=-53.43]]
	Chunk stats: Client Chunk Cache: 729, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (241,35,-53), Chunk: (at 1,2,11 in 15,-4; contains blocks 240,0,-64 to 255,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 52856 game time, 792000 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:4b42664:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1334388560 bytes (1272 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bleachhack: BleachHack 5353
		com_github_vatuu_discord-rpc: discord-rpc 1.6.2
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.10.6+build.214
		minecraft: Minecraft 1.16.4
	Launched Version: fabric-loader-0.10.6+build.214-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by DotDivee** [comment]
Lol #169

**Comment by 22s** [comment]
stupid kotlim garbage gross

**Comment by BleachDrinker420** [comment]
kotlim bad jawa good
