### ISSUE TITLE
crash with optifabric & latest optifine

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/bleachhack-1.14#95]
bleachhack version: latest (13.2)
mc version: 1.16.1
fabric api version: 
fabric loader version: 
optifine version: OptiFine 1.16.1 HD U G2 pre5

the issue: when hovering over shulkers with the Peek hack enabled, the game crashes.
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/21/20 3:20 PM
Description: Rendering screen

java.lang.IllegalStateException: Already building!
	at net.minecraft.class_287.method_1328(class_287.java:319)
	at net.minecraft.class_437.method_25417(class_437.java:174)
	at net.minecraft.class_437.method_25409(class_437.java:120)
	at net.minecraft.class_481.method_25409(class_481.java:729)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_481.method_25394(class_481.java:690)
	at net.minecraft.class_757.method_3192(class_757.java:807)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1328(class_287.java:319)
	at net.minecraft.class_437.method_25417(class_437.java:174)
	at net.minecraft.class_437.method_25409(class_437.java:120)
	at net.minecraft.class_481.method_25409(class_481.java:729)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_481.method_25394(class_481.java:690)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (241, 121). Absolute: (483.000000, 242.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['ayunami2000'/141657, l='ClientLevel', x=-4141.67, y=50.00, z=5632.40]]
	Chunk stats: Client Chunk Cache: 729, 283
	Level dimension: minecraft:flatlands
	Level spawn location: World: (-5760,54,3148), Chunk: (at 0,3,12 in -360,196; contains blocks -5760,0,3136 to -5745,255,3151), Region: (-12,6; contains chunks -384,192 to -353,223, blocks -6144,0,3072 to -5633,255,3583)
	Level time: 71936 game time, 30000 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:616)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 739519120 bytes (705 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bleachhack: BleachHack 13.37
		com_github_vatuu_discord-rpc: discord-rpc 1.6.2
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5
	OptiFine Build: 20200719-015630
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by 22s** [comment]
1.16.1 release isnt optifine compatible, only 1.14.4-optifine release is. (because its actually marked to work with optifine)

**Comment by BleachDrinker420** [comment]
bruh there isn't even a 1.16.1 version, but i'll see

**Comment by ayunami2000** [comment]
im using the snapshot one, it works on 1.16.1

**Comment by BleachDrinker420** [comment]
Ok i fixed a few peek issues in the latest commit, test if it works @ayunami2000 
[bleachhack-1.16.1-git-513.zip](https://github.com/BleachDrinker420/bleachhack-1.14/files/4958355/bleachhack-1.16.1-git-513.zip)
(the jar is inside the zip because github is retarded)

**Comment by ayunami2000** [comment]
@BleachDrinker420 it doesnt crash but no peek is shown at all
also this is what the map looks like:
(cursor beside map)
![image](https://user-images.githubusercontent.com/24785136/88145499-7da3b580-cbc8-11ea-850b-68b3eb683bbb.png)
(cursor on map)
![image](https://user-images.githubusercontent.com/24785136/88145546-9318df80-cbc8-11ea-907b-df6288d71303.png)

**Comment by BleachDrinker420** [comment]
uhhh

**Comment by ayunami2000** [comment]
also this could be due to optifabric bad (it is being discontinued sadly) but i dont wanna lose the shader support that optifine provides. idk if it's possible to work around or maybe fix the issues that optifabric has?? (if it's optifabric's fault)

**Comment by BleachDrinker420** [comment]
ah yes, lemme just code optifine 2 real quick

**Comment by BleachDrinker420** [comment]
nah, thats too much work

**Comment by ayunami2000** [comment]
optifabric hooks into the optifine jar tho so its probably just some small issue with it converting optifine to fabric (idk tho) (also idk if its due to optifabric still)

**Comment by ayunami2000** [comment]
well at least it doesnt crash tho tbh not too worried about this bc i dont usually use maps lol

**Comment by ayunami2000** [comment]
actually i dont think i ever tested if it was optifine specific or not i dont remember
